
services:


  m1m_service:
    build:
      context: m1m
      dockerfile: ./Dockerfile
    volumes:
      - ./m1m/src:/src
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: m1m
      TOKEN_URL: http://localhost/api/accounts/auth/jwt/login
      API_GATEWAY: http://nginx/api
      REDIS_HOST: redis

    depends_on:
      - postgres
      - redis
    container_name: m1m_service
    expose:
      - 80
    networks:
      - m1m_network
      - redis_network


networks:
  m1m_network:
