"""empty message

Revision ID: 67788a15d349
Revises: f377e8d7431a
Create Date: 2024-10-31 17:44:27.141070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = False

# revision identifiers, used by Alembic.
revision: str = '67788a15d349'
down_revision: Union[str, None] = 'f377e8d7431a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cases_executor_id_fkey', 'cases', type_='foreignkey')
    op.drop_constraint('cases_creator_id_fkey', 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'users', ['executor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cases', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key('cases_creator_id_fkey', 'cases', 'users', ['creator_id'], ['id'])
    op.create_foreign_key('cases_executor_id_fkey', 'cases', 'users', ['executor_id'], ['id'])
    # ### end Alembic commands ###
