"""empty message

Revision ID: 79d84e3a75e3
Revises: 67788a15d349
Create Date: 2024-10-31 21:42:18.819600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = False

# revision identifiers, used by Alembic.
revision: str = '79d84e3a75e3'
down_revision: Union[str, None] = '67788a15d349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('case_answers_answer_to_id_fkey', 'case_answers', type_='foreignkey')
    op.create_foreign_key(None, 'case_answers', 'cases', ['answer_to_id'], ['id'], ondelete='CASCADE')
    op.drop_column('case_answers', 'text')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_answers', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'case_answers', type_='foreignkey')
    op.create_foreign_key('case_answers_answer_to_id_fkey', 'case_answers', 'cases', ['answer_to_id'], ['id'])
    # ### end Alembic commands ###
