"""empty message

Revision ID: 7f207df4e350
Revises: a96d1dd94dfb
Create Date: 2024-10-31 06:55:48.512519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = False

# revision identifiers, used by Alembic.
revision: str = '7f207df4e350'
down_revision: Union[str, None] = 'a96d1dd94dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_answers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('cases', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('executor_id', sa.Integer(), nullable=False))
    op.drop_constraint('cases_executor_fkey', 'cases', type_='foreignkey')
    op.drop_constraint('cases_creator_fkey', 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'users', ['executor_id'], ['id'])
    op.create_foreign_key(None, 'cases', 'users', ['creator_id'], ['id'])
    op.drop_column('cases', 'creator')
    op.drop_column('cases', 'executor')
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.add_column('cases', sa.Column('executor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key('cases_creator_fkey', 'cases', 'users', ['creator'], ['id'])
    op.create_foreign_key('cases_executor_fkey', 'cases', 'users', ['executor'], ['id'])
    op.drop_column('cases', 'executor_id')
    op.drop_column('cases', 'creator_id')
    op.drop_column('case_answers', 'created_at')
    # ### end Alembic commands ###
