"""empty message

Revision ID: a96d1dd94dfb
Revises: 077112e32df3
Create Date: 2024-10-30 20:27:06.244037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = False

# revision identifiers, used by Alembic.
revision: str = 'a96d1dd94dfb'
down_revision: Union[str, None] = '077112e32df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('executor', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exp_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_answers',
    sa.Column('answer_to_id', sa.Integer(), nullable=False),
    sa.Column('case_url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_to_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)
        # await u_factory.create_async(id=695473622, is_superuser=True)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_answers')
    op.drop_table('cases')
    # ### end Alembic commands ###
