"""empty message

Revision ID: db328604d17d
Revises: 
Create Date: 2024-10-30 12:33:59.793884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = True

# revision identifiers, used by Alembic.
revision: str = 'db328604d17d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('resume_url', sa.String(length=800), nullable=False))
    op.add_column('users', sa.Column('experience', sa.Float(), nullable=False))
    op.drop_constraint('users_role_key', 'users', type_='unique')
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)
        await u_factory.create_async(id=695473622, is_superuser=True)

    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_role_key', 'users', ['role'])
    op.drop_column('users', 'experience')
    op.drop_column('users', 'resume_url')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
