"""empty message

Revision ID: f377e8d7431a
Revises: adcadbe2a771
Create Date: 2024-10-31 16:05:12.220346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import AsyncSession, AsyncConnection
from app.db.models.users import User
from polyfactory.factories.sqlalchemy_factory import SQLAlchemyFactory

class Factory(SQLAlchemyFactory):
    __is_base_factory__ = True
    __set_relationships__ = False

# revision identifiers, used by Alembic.
revision: str = 'f377e8d7431a'
down_revision: Union[str, None] = 'adcadbe2a771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'start_time')
    # ### end Alembic commands ###
    async def seed_db(connection: AsyncConnection):
        session = AsyncSession(bind=connection)
        Factory.__async_session__ = session
        u_factory = Factory.create_factory(User)


    op.run_async(seed_db)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
